In [1]:
import numpy as np

In [2]:
matrix_d = np.array([[1,1,1, 2,0], [3, 6, 6, 7, 4], [4, 5, 3, 8, 0]])
matrix_d

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [3]:
matrix_d[0,0]

1

In [4]:
type(matrix_d[0,0])

numpy.int64

In [6]:
matrix_d[0, 0:1]

array([1])

In [7]:
type(matrix_d[0,0:1])

numpy.ndarray

In [8]:
matrix_d[0:1, 0:1]

array([[1]])

In [10]:
type(matrix_d[0:1, 0:1])

numpy.ndarray

In [11]:
matrix_d[0, 0:1].shape

(1,)

In [12]:
matrix_d[0:1, 0:1].shape

(1, 1)

In [14]:
matrix_d[0:1, 0:1].shape

(1, 1)

In [18]:
matrix_d[0:1, 0:1].squeeze()

array(1)

In [19]:
matrix_d[0:1, 0:1].squeeze().shape

()

In [20]:
np.squeeze(matrix_d[0:1, 0:1])

array(1)