In [1]:
import numpy as np

In [2]:
array_range = np.arange(30)
array_range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [3]:
array_range1 = np.arange(start=30)
array_range1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
array_range_2 = np.arange(start=5, stop = 30)
array_range_2

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [5]:
array_range_3 = np.arange(start = 3, stop = 30, step = 2.5)
array_range_3

array([ 3. ,  5.5,  8. , 10.5, 13. , 15.5, 18. , 20.5, 23. , 25.5, 28. ])

In [6]:
array_range_4 = np.arange(start = 4, stop = 32, step = 2, dtype= np.float32)
array_range_4

array([ 4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26., 28.,
       30.], dtype=float32)