In [1]:
import numpy as np

In [2]:
lending_co_data_n = np.loadtxt("Lending-company-Numeric.csv", delimiter=",")

In [3]:
np.isnan(lending_co_data_n)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [5]:
np.isnan(lending_co_data_n).sum()

0

In [7]:
lending_co_nan = np.loadtxt("Lending-company-Numeric-NAN.csv", delimiter=";")

ValueError: could not convert string to float: ''

In [8]:
lending_co_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter=";")

In [9]:
np.isnan(lending_co_nan)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [10]:
np.isnan(lending_co_nan).sum()

260

In [12]:
lending_co_nan2 = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter =";", filling_values=0)

In [13]:
np.isnan(lending_co_nan2)

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       ...,
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [14]:
np.isnan(lending_co_nan2).sum()

0

In [17]:
temp_fill = np.nanmax(lending_co_nan).round(2) + 1

In [18]:
temp_fill

64002.0

In [19]:
lending_co_nan3 = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter =";", filling_values = temp_fill)

In [20]:
lending_co_nan3

array([[2.0000e+03, 4.0000e+01, 3.6500e+02, 3.1210e+03, 4.2410e+03,
        1.3621e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 3.0610e+03, 4.1710e+03,
        1.5041e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.1600e+03, 3.2800e+03,
        1.5340e+04],
       ...,
       [6.4002e+04, 4.0000e+01, 3.6500e+02, 4.2010e+03, 5.0010e+03,
        1.6600e+04],
       [1.0000e+03, 4.0000e+01, 3.6500e+02, 2.0800e+03, 3.3200e+03,
        1.5600e+04],
       [2.0000e+03, 4.0000e+01, 3.6500e+02, 4.6010e+03, 4.6010e+03,
        1.6600e+04]])