In [1]:
import numpy as np

In [2]:
lending_co = np.loadtxt("Lending-company-Numeric.csv", delimiter = ",")
lending_co

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
np.concatenate((lending_co[0,:], lending_co[1, :]))

array([ 2000.,    40.,   365.,  3121.,  4241., 13621.,  2000.,    40.,
         365.,  3061.,  4171., 15041.])

In [4]:
lending_co_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ";")

temp_fill = np.nanmax(lending_co_nan).round(2) + 1
temp_mean = np.nanmean(lending_co_nan, axis = 0).round(2)

lending_co_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ";", filling_values = temp_fill)

for i in range(lending_co_nan.shape[1]):
    lending_co_nan[:, i] = np.where(lending_co_nan[:, i] == temp_fill, temp_mean[i], lending_co_nan[:, i])
    
lending_co_nan

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [5]:
np.concatenate((lending_co, lending_co_nan)) # the second dataset is at the bottom

array([[ 2000.  ,    40.  ,   365.  ,  3121.  ,  4241.  , 13621.  ],
       [ 2000.  ,    40.  ,   365.  ,  3061.  ,  4171.  , 15041.  ],
       [ 1000.  ,    40.  ,   365.  ,  2160.  ,  3280.  , 15340.  ],
       ...,
       [ 2250.25,    40.  ,   365.  ,  4201.  ,  5001.  , 16600.  ],
       [ 1000.  ,    40.  ,   365.  ,  2080.  ,  3320.  , 15600.  ],
       [ 2000.  ,    40.  ,   365.  ,  4601.  ,  4601.  , 16600.  ]])

In [6]:
np.concatenate((lending_co, lending_co_nan)).shape

(2086, 6)

In [7]:
np.concatenate((lending_co, lending_co_nan), axis = 1) # two arrays side by side

array([[ 2000.,    40.,   365., ...,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365., ...,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365., ...,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365., ...,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365., ...,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365., ...,  4601.,  4601., 16600.]])

In [8]:
np.concatenate((lending_co, lending_co_nan), axis = 1).shape

(1043, 12)