In [1]:
import numpy as np

np.empty(), np.zeros(), np.ones(), np.full()

In [2]:
array_empty = np.empty(shape=(2, 3))
array_empty

array([[-3.10503618e+231, -1.49457171e-154,  1.97626258e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000]])

In [4]:
array_zeros = np.zeros(shape =(2,3))
array_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
array_0s = np.zeros(shape=(2, 3), dtype= np.int8)
array_0s

array([[0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [7]:
array_ones = np.ones(shape =(2, 3))
array_ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
array_1s = np.ones(shape=(4,5), dtype= np.int8)
array_1s

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [11]:
array_full1 = np.full(shape=(2, 3), fill_value = 2)
array_full1 

array([[2, 2, 2],
       [2, 2, 2]])

In [12]:
array_fill2 = np.full(shape=(4, 6), fill_value="the-six-nine")
array_fill2

array([['the-six-nine', 'the-six-nine', 'the-six-nine', 'the-six-nine',
        'the-six-nine', 'the-six-nine'],
       ['the-six-nine', 'the-six-nine', 'the-six-nine', 'the-six-nine',
        'the-six-nine', 'the-six-nine'],
       ['the-six-nine', 'the-six-nine', 'the-six-nine', 'the-six-nine',
        'the-six-nine', 'the-six-nine'],
       ['the-six-nine', 'the-six-nine', 'the-six-nine', 'the-six-nine',
        'the-six-nine', 'the-six-nine']], dtype='<U12')