In [1]:
import numpy as np
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [2]:
array_RG = gen(pcg(365))
array_RG.integers(10, size=(2, 3))

array([[0, 7, 6],
       [7, 8, 6]])

In [4]:
array_RG2 = gen(pcg(seed= 365))
array_RG2.integers(low= 10, high = 100, size=(5,5))

array([[18, 78, 64, 78, 84],
       [66, 67, 28, 10, 69],
       [45, 15, 37, 74, 96],
       [19, 21, 89, 73, 54],
       [53, 84, 66, 51, 92]])

In [6]:
array_rand = gen(pcg(seed = 365))
array_rand.random( size = (5, 5))

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736],
       [0.29787156, 0.4996155 , 0.4865245 , 0.62740703, 0.54952637],
       [0.64894629, 0.04411757, 0.7206516 , 0.84594003, 0.17159792]])

In [7]:
array_cho = gen(pcg(seed = 100))
array_cho.choice([1, 2, 3, 4, 5], size = (5, 5))

array([[4, 5, 1, 3, 1],
       [2, 3, 1, 3, 5],
       [5, 3, 3, 4, 5],
       [5, 1, 4, 4, 1],
       [3, 5, 4, 2, 2]])