In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1, 0, 9, 2, 2], [2, 23, 4, 5, 1], [0, 2, 3, 4, 1]])
matrix_a

array([[ 1,  0,  9,  2,  2],
       [ 2, 23,  4,  5,  1],
       [ 0,  2,  3,  4,  1]])

In [3]:
array_empty_like = np.empty_like(matrix_a)

In [4]:
array_empty_like

array([[                  0,                   0, 4607182418800017408,
        4589168020290535424, 4598175219545276416],
       [4607182418800017408, 4607182418800017408, 4607182418800017408,
        4607182418800017408, 4617385886705778688],
       [4612248968380809216, 4607182418800017408, 4625196817309499392,
        4616189618054758400, 4607182418800017408]])

In [5]:
array_0_like = np.zeros_like(matrix_a)
array_0_like

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])