In [1]:
import numpy as np

In [2]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

In [3]:
print(array_a)

[1 2 3]


In [4]:
array_a.shape

(3,)

In [5]:
array_b = np.array([[7, 8, 9], [10, 11, 12]])
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
print(array_b)

[[ 7  8  9]
 [10 11 12]]


In [7]:
array_b.shape

(2, 3)

In [8]:
array_b.shape[0] # no. of rows

2

In [9]:
array_b.shape[1] # no. of columns

3

In [10]:
array_c = np.array(13)
array_c

array(13)

In [11]:
print(array_c)

13


In [12]:
array_c.shape # no length or shape

()

In [14]:
array_d = np.array([15])
array_d

array([15])

In [15]:
print(array_d)

[15]


In [16]:
array_d.shape

(1,)