In [1]:
import numpy as np

In [4]:
array_a = np.array([1, 2, 3])
array_b = np.array([[1], [2]])
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
array_a

array([1, 2, 3])

In [6]:
array_b

array([[1],
       [2]])

In [7]:
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

Broadcasting

In [8]:
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [9]:
matrix_c + array_a

array([[2, 4, 6],
       [5, 7, 9]])

In [10]:
np.add(array_b, matrix_c)

array([[2, 3, 4],
       [6, 7, 8]])

In [11]:
array_b + matrix_c

array([[2, 3, 4],
       [6, 7, 8]])

Type Casting

In [13]:
np.add(array_b, matrix_c, dtype = "float64")

array([[2., 3., 4.],
       [6., 7., 8.]])

Running Over an Axis

In [14]:
np.mean(matrix_c, axis=0) # the axis is for the rows

array([2.5, 3.5, 4.5])

In [15]:
np.mean(matrix_c, axis=1) #mean of every row

array([2., 5.])