In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1, 2, 3], [4, 5, 6]])
matrix_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
matrix_a[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
matrix_a[0:1]

array([[1, 2, 3]])

In [5]:
matrix_a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
matrix_a[:1]

array([[1, 2, 3]])

In [7]:
matrix_a[1:]

array([[4, 5, 6]])

In [9]:
matrix_a[0]

array([1, 2, 3])

In [10]:
matrix_a[:1]

array([[1, 2, 3]])

In [11]:
matrix_a[0].shape

(3,)

In [12]:
matrix_a[:1].shape

(1, 3)

In [13]:
matrix_a[:-1]

array([[1, 2, 3]])

In [14]:
matrix_a[:,1:] # left of the comma is for the rows and right of it is for the columns

array([[2, 3],
       [5, 6]])

In [15]:
matrix_a[1:,1:]

array([[5, 6]])

In [16]:
matrix_b = np.array([[1, 1, 1, 2, 0], [3, 6, 6, 7, 4], [4, 5, 3, 8, 0]])
matrix_b

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [18]:
matrix_b[::2, ::] # every other row

array([[1, 1, 1, 2, 0],
       [4, 5, 3, 8, 0]])

In [19]:
matrix_b[::, ::2] # every other column

array([[1, 1, 0],
       [3, 6, 4],
       [4, 3, 0]])

In [20]:
matrix_b[::2, ::2]

array([[1, 1, 0],
       [4, 3, 0]])

In [21]:
matrix_b[::-2, ::2]

array([[4, 3, 0],
       [1, 1, 0]])

Conditional SLicing

In [22]:
matrix_c = np.array([[1,1,1, 2, 0], [3, 6, 6, 7, 4], [4, 5, 3, 8, 0]])
matrix_c

array([[1, 1, 1, 2, 0],
       [3, 6, 6, 7, 4],
       [4, 5, 3, 8, 0]])

In [23]:
matrix_c[:,1:]

array([[1, 1, 2, 0],
       [6, 6, 7, 4],
       [5, 3, 8, 0]])

In [28]:
matrix_c[:,0]

array([1, 3, 4])

In [29]:
matrix_c[:, 0] > 2

array([False,  True,  True])

In [30]:
matrix_c[:,:] >2

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [32]:
matrix_c[matrix_c[:,:] > 2]

array([3, 6, 6, 7, 4, 4, 5, 3, 8])

In [33]:
matrix_c[(matrix_c[:,:] % 2 ==0 ) & (matrix_c[:,:] > 4)]

array([6, 6, 8])

In [34]:
matrix_c[(matrix_c[:,:] % 2 == 0) | (matrix_c[:,:] >4)]

array([2, 0, 6, 6, 7, 4, 4, 5, 8, 0])