In [1]:
import numpy as np

In [2]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array_a[0,-1] = 8

In [4]:
array_a

array([[1, 2, 8],
       [4, 5, 6]])

In [5]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [6]:
array_a[:,0] = 7
array_a

array([[7, 9, 9],
       [7, 5, 6]])

In [8]:
list_a = [5, 7, 9]
array_a[0] = list_a
array_a

array([[5, 7, 9],
       [7, 5, 6]])

In [9]:
type(array_a[0])

numpy.ndarray

In [10]:
array_a[:] = 7

In [11]:
array_a

array([[7, 7, 7],
       [7, 7, 7]])