In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1, 0, 0, 3, 1], [3, 6, 6, 2, 9], [4, 5, 3, 8, 0]])
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [3]:
np.mean(matrix_a)

3.4

In [4]:
np.mean(matrix_a[0])

1.0

In [5]:
np.mean(matrix_a[:, 0])

2.6666666666666665

In [6]:
np.mean(matrix_a, axis = 0) # for every column

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [7]:
np.mean(matrix_a, axis = 1) # for every row

array([1. , 5.2, 4. ])

In [8]:
matrix_a.mean()

3.4

In [9]:
np.min(matrix_a)

0

In [10]:
np.min(matrix_a, axis = 0)

array([1, 0, 0, 2, 0])

In [11]:
np.min(matrix_a, axis = 1)

array([0, 2, 0])

In [13]:
np.amin(matrix_a)

0

In [14]:
np.minimum(matrix_a[0], matrix_a[2])

array([1, 0, 0, 3, 0])

In [15]:
np.minimum.reduce(matrix_a) # shows the least number of earch element in the matrix

array([1, 0, 0, 2, 0])

In [17]:
np.min(matrix_a, axis = 0) # same as the above

array([1, 0, 0, 2, 0])

In [18]:
np.max(matrix_a)

9

In [19]:
np.amax(matrix_a)

9

In [20]:
np.maximum.reduce(matrix_a)

array([4, 6, 6, 8, 9])