In [1]:
import numpy as np

In [2]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
array_a[0]

array([1, 2, 3])

In [5]:
array_a[1]

array([4, 5, 6])

In [6]:
array_a[0][1]

2

In [7]:
array_a[1,0]

4

In [8]:
array_a[0,1]

2

In [9]:
array_a[:, 0]

array([1, 4])

In [10]:
array_b= np.array([1, 2, 3])
array_b[-1]

3

In [11]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array_a[-1]

array([4, 5, 6])

In [13]:
array_a[:,-1]

array([3, 6])