In [1]:
import numpy as np

In [2]:
array_b = np.array([[1, 2, 3], [4, 5, 6]])
array_a = np.array([7, 8, 9])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
array_a

array([7, 8, 9])

In [4]:
array_a + 2

array([ 9, 10, 11])

In [5]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [6]:
array_a + array_b[0]

array([ 8, 10, 12])

In [7]:
array_a + array_b # they have to be the same length. if 2d-> the length of the rows.

array([[ 8, 10, 12],
       [11, 13, 15]])