In [1]:
import numpy as np

In [2]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [3]:
array_RG = gen(pcg())
array_RG.normal()

1.940909997135894

In [4]:
array_RG2 = gen(pcg())
array_RG2.normal(size= 5)

array([ 0.8108473 ,  0.68192369, -0.24269688,  0.78072272, -1.24235385])

In [5]:
array_RGT = gen(pcg())
array_RGT.normal(size=(4, 5))

array([[-0.84098529, -1.39047689,  0.33498917, -1.12569925, -0.1246738 ],
       [-2.1176583 ,  1.65561406,  1.09315562,  0.97165025,  0.43572908],
       [ 0.10469026,  0.98403514, -1.89986978,  0.78603335, -0.46985388],
       [ 0.28393425,  0.63985005, -1.04615703, -0.98218158,  0.30462271]])

In [6]:
array_RGS = gen(pcg(seed = 212))
array_RGS.normal(size = (2, 3))

array([[-0.39921299, -1.40754585,  1.21409872],
       [ 0.31056865,  1.13507559, -0.18854173]])