Import numpy

In [1]:
import numpy as np

Declaring scalars, Vectors and Matrices

Scalars

In [2]:
s = 5

In [3]:
s

5

Vectors. By default "v" is a row vector

In [4]:
v = np.array([5, -2, 4])

In [5]:
v

array([ 5, -2,  4])

Matrices

In [7]:
m = np.array([[5, 12, 6], [-3, 0, 14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

Data Types

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [14]:
s_array = np.array(5)
s_array # this is a scalar

array(5)

In [15]:
type(s_array)

numpy.ndarray

Data Shapes

In [16]:
m.shape

(2, 3)

In [17]:
v.shape

(3,)

Reshaping

1. a row vector

In [19]:
v.reshape(1, 3)

array([[ 5, -2,  4]])

2. a column vector

In [20]:
v.reshape(3, 1)

array([[ 5],
       [-2],
       [ 4]])

In [21]:
v

array([ 5, -2,  4])

In [22]:
s_array.shape # a scalar has no shape

()

Tensors

Creating a Tensor

In [23]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [24]:
m2 = np.array([[9, 8 , 7], [1, 3, -5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [25]:
t = np.array([m1, m2])

In [26]:
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Checking its shape

In [27]:
t.shape

(2, 2, 3)

Creating a Tenasor manually

In [28]:
t_manual = np.array([[[5, 12, 6], [-3, 0, 14]], [[9, 8, 7], [1, 3, -5]]])

In [30]:
t_manual

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

Addition

In [31]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [32]:
m3 = np.array([[5, 3], [-2, 4]])
m4 = np.array([[7, -5], [3, 8]])

In [33]:
m3

array([[ 5,  3],
       [-2,  4]])

In [34]:
m4

array([[ 7, -5],
       [ 3,  8]])

In [35]:
m3 - m4

array([[-2,  8],
       [-5, -4]])

In [36]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [37]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [40]:
v

array([ 5, -2,  4])

In [41]:
v + 1

array([ 6, -1,  5])

In [42]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [43]:
m1 + np.array([1])

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [44]:
v

array([ 5, -2,  4])

In [45]:
v + np.array([1])

array([ 6, -1,  5])

Transposing Matrices

In [46]:
a = np.array([[5, 12, 6], [-3, 0, 14]])
a

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [47]:
a.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [48]:
b = np.array([[5, 3], [-2, 4]])
b

array([[ 5,  3],
       [-2,  4]])

In [49]:
b.T

array([[ 5, -2],
       [ 3,  4]])

In [50]:
c = np.array([[4, 5], [8, 12], [-2, -3], [19, 0]])
c

array([[ 4,  5],
       [ 8, 12],
       [-2, -3],
       [19,  0]])

In [51]:
c.T

array([[ 4,  8, -2, 19],
       [ 5, 12, -3,  0]])

Transposing Scalars

In [52]:
s = np.array([5])
s

array([5])

In [53]:
s.T

array([5])

Transposing Vectors

In [54]:
v3 = np.array([1, 2 ,3])
v3

array([1, 2, 3])

In [55]:
v3.T

array([1, 2, 3])

In [56]:
v3.shape

(3,)

In [58]:
v3_reshaped = v3.reshape(1, 3)
v3_reshaped

array([[1, 2, 3]])

In [59]:
v3_reshaped.T

array([[1],
       [2],
       [3]])

Vector Multiplication

In [61]:
vx = np.array([2, 8, -4])
vy = np.array([1, -7, 3])

In [62]:
vx, vy

(array([ 2,  8, -4]), array([ 1, -7,  3]))

In [63]:
np.dot(vx, vy)

-66

In [64]:
vu = np.array([0, 2, 5, 8])
vw = np.array([20, 3, 4, -1])

In [65]:
vu, vw

(array([0, 2, 5, 8]), array([20,  3,  4, -1]))

In [66]:
np.dot(vu, vw)

18

Scalar * Vector => We get a vector with the same length, each vector will be scaled.

In [68]:
vx

array([ 2,  8, -4])

In [69]:
5 * vx

array([ 10,  40, -20])

Scalar * Matrix => The shape of the matrix doesn't change. it just gets scaled.

In [72]:
ma = np.array([[5, 12, 6], [-3, 0, 14]])
ma

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [73]:
5*ma

array([[ 25,  60,  30],
       [-15,   0,  70]])

Matrix * Matrix

In [74]:
exB = np.array([[2, -1], [8, 0], [3, 0]])
exB

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [75]:
np.dot(ma, exB)

array([[124,  -5],
       [ 36,   3]])

In [78]:
bigM1 = np.array([[-12, 5, -5, 1, 6], [6, -2, 0, 0, -3], [10, 2, 0, 8, 0], [9, -4, 8, 3, -6]])
bigM1

array([[-12,   5,  -5,   1,   6],
       [  6,  -2,   0,   0,  -3],
       [ 10,   2,   0,   8,   0],
       [  9,  -4,   8,   3,  -6]])

In [81]:
bigM2 = np.array([[6, -1], [8, -4], [ 2, -2], [7, 4], [-6, -9]])
bigM2

array([[ 6, -1],
       [ 8, -4],
       [ 2, -2],
       [ 7,  4],
       [-6, -9]])

In [82]:
np.dot(bigM1, bigM2)

array([[-71, -48],
       [ 38,  29],
       [132,  14],
       [ 95,  57]])