In [1]:
import numpy as np

In [2]:
lending_co = np.loadtxt("Lending-company-numeric.csv", delimiter = ',')
lending_co

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
lending_co = np.loadtxt("Lending-company-numeric.csv", delimiter = ',')[:8]
lending_co

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.]])

In [4]:
np.random.shuffle(lending_co)

In [5]:
lending_co

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3201.,  4141., 14141.],
       [ 2000.,    50.,   365.,  1851.,  3251., 17701.],
       [ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3971.,  4131., 15351.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.]])

In [6]:
lending_co = np.loadtxt("Lending-company-numeric.csv", delimiter = ',')
lending_co

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [7]:
from numpy.random import shuffle

In [8]:
shuffle(lending_co)

In [9]:
lending_co

array([[ 2000.,    40.,   365.,  3261.,  4601., 15781.],
       [ 1000.,    50.,   365.,  2050.,  3150., 19250.],
       [ 2000.,    40.,   365.,  2881.,  4081., 11901.],
       ...,
       [ 2000.,    40.,   365.,  3401.,  7401., 16600.],
       [ 1000.,    40.,   365.,  2280.,  3400., 15600.],
       [ 2000.,    50.,   365.,  3750.,  5250., 20250.]])

In [10]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [11]:
array_rg = gen(pcg())
array_rg.shuffle(lending_co)
lending_co

array([[ 1000.,    40.,   365., 12500., 12500., 15600.],
       [ 2000.,    40.,   365.,  3941.,  3941.,  8201.],
       [ 1000.,    40.,   365.,  2160.,  3360., 15600.],
       ...,
       [ 2000.,    40.,   365.,  2951.,  3951., 12341.],
       [ 4000.,    50.,   365.,  7000.,  8500., 22250.],
       [ 2000.,    40.,   365.,  3120.,  3960.,  9040.]])