In [1]:
import numpy as np

In [2]:
matrix_a = np.array([[1, 0, 0, 3, 1], [3, 6, 6, 2, 9], [4, 5, 3, 8, 0]])
matrix_a

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [3]:
np.ptp(matrix_a)

9

In [4]:
np.ptp(matrix_a, axis = 0)

array([3, 6, 6, 6, 9])

In [6]:
np.ptp(matrix_a, axis = 1)

array([3, 7, 8])

In [7]:
np.sort(matrix_a, axis = None) # will flatten the array

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [8]:
np.percentile(matrix_a, 70)

4.799999999999999

In [10]:
np.percentile(matrix_a, 70, interpolation = "midpoint")

4.5

In [11]:
np.percentile(matrix_a, 70, interpolation = "higher")

5

In [12]:
np.percentile(matrix_a, 70, interpolation = "lower")

4

In [14]:
np.percentile(matrix_a, 70, interpolation = "nearest")

5

In [15]:
np.percentile(matrix_a, 50) # will give me the median

3.0

In [16]:
np.quantile(matrix_a, 0.7)

4.799999999999999

In [17]:
np.quantile(matrix_a, 0.7, interpolation = "nearest")

5