In [1]:
import numpy as np

In [2]:
lending_co = np.loadtxt("Lending-company-Numeric.csv", delimiter = ",")
lending_co

array([[ 2000.,    40.,   365.,  3121.,  4241., 13621.],
       [ 2000.,    40.,   365.,  3061.,  4171., 15041.],
       [ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       ...,
       [ 2000.,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [3]:
np.unique(lending_co)

array([-2870., -2550., -2450., ..., 52751., 54625., 64001.])

In [4]:
np.unique(lending_co[:, 1], return_counts = True) # will get a tuple. 1- for the unique values 2- their frequency

(array([ 35.,  40.,  50., 125., 165.]), array([  4, 567, 451,  19,   2]))

In [5]:
np.unique(lending_co[:, 1], return_counts = True, return_index = True) # index of these values

(array([ 35.,  40.,  50., 125., 165.]),
 array([327,   0,   4,  19,  27]),
 array([  4, 567, 451,  19,   2]))